#!/bin/bash

if [ $# -lt 1 ]
then
        echo "Usage : $0 URL"
        exit
fi

filepath=$1
filename=`basename "$1"`
echo filepath = $filepath
echo filename = $filename

#filepath should be set to the name(with optional path) of the file in question
 ext=${filepath##*\.}

echo "Downloading into file named $filename"
curl -o $filename $1
